import { useEffect, useState } from 'react';
import { Calendar, Clock, MapPin, UserRound } from 'lucide-react';
import { catalogsApi, professionalApi, schedulingErrorMessage } from '../api/schedulingApi';
import type { CatalogItem, ProfessionalAppointment } from '../types';
import { AppointmentHistory } from './AppointmentHistory';
import { bogotaNow, bogotaToday, dateTime, weekRange } from './format';

function ClosureActions({ appointment, onClosed }: { appointment: ProfessionalAppointment; onClosed: (message: string) => void }) {
  const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  if (appointment.endAt.slice(0, 16) > bogotaNow().slice(0, 16)) return <p className="mt-2 text-xs text-slate-500">Podrás cerrar la atención cuando finalice el horario.</p>;
  const close = async (result: 'COMPLETED' | 'NO_SHOW') => { setBusy(true); setError(''); try { await professionalApi.close(appointment.id, result, reason.trim()); onClosed(result === 'COMPLETED' ? 'Atención registrada como completada.' : 'Inasistencia registrada.'); } catch (cause) { setError(schedulingErrorMessage(cause, 'La cita ya fue cerrada o aún no ha finalizado.')); } finally { setBusy(false); } };
  return <div className="mt-3 space-y-2"><input value={reason} maxLength={500} onChange={(event) => setReason(event.target.value)} placeholder="Observación opcional del cierre" aria-label="Observación del cierre" className="p-2 border rounded-lg text-xs w-full md:max-w-md bg-white" /><div className="flex gap-2"><button type="button" disabled={busy} onClick={() => close('COMPLETED')} className="px-3 py-2 text-xs bg-emerald-600 text-white rounded-xl disabled:opacity-50">Atendida</button><button type="button" disabled={busy} onClick={() => close('NO_SHOW')} className="px-3 py-2 text-xs bg-amber-600 text-white rounded-xl disabled:opacity-50">No asistió</button></div>{error && <p role="alert" className="text-xs text-red-700">{error}</p>}</div>;
}

/** PROFESSIONAL own APPROVED agenda by day/week and location (HU-029) with attendance closure (HU-030). */
export function ProfessionalAgendaTab() {
  const [mode, setMode] = useState<'day' | 'week'>('day'); const [date, setDate] = useState(bogotaToday); const [locationId, setLocationId] = useState(''); const [locations, setLocations] = useState<CatalogItem[]>([]); const [items, setItems] = useState<ProfessionalAppointment[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [refresh, setRefresh] = useState(0);
  const range = mode === 'day' ? { from: date, to: date } : weekRange(date);
  useEffect(() => { catalogsApi.locations().then(setLocations).catch(() => undefined); }, []);
  useEffect(() => { if (!date) return; let current = true; setLoading(true); setError(''); professionalApi.agenda({ ...range, locationId: locationId || undefined }).then((rows) => { if (current) setItems(rows); }).catch((cause) => { if (current) setError(schedulingErrorMessage(cause)); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [mode, date, locationId, refresh]);
  return <section className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 space-y-4">
    <div className="flex flex-wrap gap-3 items-end justify-between"><div><h2 className="text-lg font-bold text-slate-900">Mi agenda</h2><p className="text-sm text-slate-500">Citas aprobadas {mode === 'day' ? 'del día' : `de la semana del ${range.from} al ${range.to}`}.</p></div>
      <div className="flex flex-wrap gap-2 items-end"><div role="group" aria-label="Periodo" className="flex rounded-lg border overflow-hidden text-xs">{(['day', 'week'] as const).map((value) => <button key={value} type="button" aria-pressed={mode === value} onClick={() => setMode(value)} className={`px-3 py-2 ${mode === value ? 'bg-blue-600 text-white' : 'bg-white text-slate-600'}`}>{value === 'day' ? 'Día' : 'Semana'}</button>)}</div><label className="text-xs text-slate-600">Fecha<input aria-label="Fecha de agenda" type="date" required value={date} onChange={(event) => setDate(event.target.value)} className="block mt-1 p-2 border rounded-lg bg-white" /></label><label className="text-xs text-slate-600">Sede<select aria-label="Sede de agenda" value={locationId} onChange={(event) => setLocationId(event.target.value)} className="block mt-1 p-2 border rounded-lg bg-white max-w-[16rem]"><option value="">Todas</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div></div>
    {notice && <p role="status" className="p-3 text-sm text-emerald-800 bg-emerald-50 rounded-xl">{notice}</p>}
    {error && <p role="alert" className="p-3 text-sm text-red-700 bg-red-50 rounded-xl">{error}</p>}
    {loading ? <p className="text-sm text-slate-500">Cargando tu agenda…</p> : items.length ? <div className="grid gap-3">{items.map((item) => <article key={item.id} className="p-4 rounded-2xl border border-slate-200 bg-slate-50"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-semibold text-slate-900"><UserRound className="inline w-4 h-4 text-blue-600 mr-1" />{item.patientName}</h3><p className="text-sm text-slate-600">{item.specialtyName} · <MapPin className="inline w-3.5 h-3.5" /> {item.locationName}</p></div><span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-emerald-100 text-emerald-800 h-fit">Aprobada</span></div><p className="mt-3 text-sm text-slate-700"><Calendar className="inline w-4 h-4 text-blue-600 mr-1" />{dateTime(item.startAt)} · <Clock className="inline w-4 h-4 text-blue-600 mr-1" />{item.durationMinutes} min</p>{item.reason && <p className="mt-1 text-xs text-slate-600">Motivo de consulta: {item.reason}</p>}<ClosureActions appointment={item} onClosed={(message) => { setNotice(message); setRefresh((value) => value + 1); }} /><AppointmentHistory appointmentId={item.id} /></article>)}</div> : <p className="p-5 text-center text-sm text-slate-500 bg-slate-50 rounded-xl">No tienes citas aprobadas en este periodo.</p>}
  </section>;
}
